### ISSUE TITLE
analytical solution

### ISSUE THREAD

**Issue by aigerimhatake** [matheusAltomare/PINN#1]
Thank you for sharing your code!
I have a question regarding analytical solution of Burger's equation.
In a code after "return" you wrote a function and I cannot understant what does that expression mean? 
Thank you!

**Comment by matheusAltomare** [comment]
Thanks for the comment, my friend!

I have used the same reference used by Raissi:

https://doi.org/10.1016/0045-7930(86)90036-8

The analytical solution is the equation 2.5 .
